// Compiles knowledge/*.md into a TS module shared by the Worker and the browser.
// Run `npm run knowledge:build` after editing knowledge files; `npm test` fails if stale.
import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
const profile = readFileSync("knowledge/profile.md", "utf8");
const policy = readFileSync("knowledge/policy.md", "utf8");
const sha = createHash("sha256")
  .update(profile)
  .update("\0")
  .update(policy)
  .digest("hex");
export const generated = `// GENERATED by scripts/build_knowledge.mjs from knowledge/*.md. Do not edit.
export const KNOWLEDGE_SHA256 = ${JSON.stringify(sha)};
export const KNOWLEDGE_VERSION = ${JSON.stringify("v1-" + sha.slice(0, 12))};
export const PROFILE = ${JSON.stringify(profile)};
export const POLICY = ${JSON.stringify(policy)};
`;
if (process.argv.includes("--check")) {
  const current = readFileSync("lib/agent/knowledge.generated.ts", "utf8");
  if (current !== generated) {
    console.error(
      "lib/agent/knowledge.generated.ts is stale; run npm run knowledge:build",
    );
    process.exit(1);
  }
  console.log("Knowledge module up to date.");
} else {
  writeFileSync("lib/agent/knowledge.generated.ts", generated);
  console.log("Wrote lib/agent/knowledge.generated.ts", sha.slice(0, 12));
}
